language: node_js
node_js: node
deploy:
  provider: heroku
  api_key: 
    secure: 1a493e08-536d-44f8-bbf8-2a87b9fd7e56
  app: salty-basin-90714
  on: 
    repo: jkathan/node-shopping-list-integration-tests
