language: node_js
node_js: node
deploy:
  provider: heroku
  api_key: 
    secure: 79368ebf-23a9-4b4d-9918-7acfe9ca7dc6
  app: cryptic-stream-48593
  on:
    repo: jkathan/node-shopping-list-integration-tests
